version: "3.9"
services:
  sofa:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: nexus.int.clxnetworks.net:8089/dev/business-process-automation/sofa:latest
    ports:
      - "1234:80"
    environment:
      DEPLOYMENT_ENV: staging
      ORDERING_SERVICE_URL: https://ordering.eu1tst.bpa.unauth.int.staging.sinch.com
      SERVER_NAME: localhost:1234
      SMART_SPEC_URL: https://smart-solution.eu1tst.bpa.unauth.int.staging.sinch.com
      TOKEN_SERVICE_URL: https://sso.admin-portal.int.staging.sinch.com
      AUTH_CLIENT_CREDENTIALS: Basic ADD CREDENTIALS HERE
      ADMIN_PORTAL_HOME_URL: https://admin.int.staging.sinch.com/
  apache-exporter:
    image: lusotycoon/apache-exporter:v0.11.0
    ports:
      - "9117:9117"
    command: "--scrape_uri=http://sofa/server-status/?auto"
