kind: Secret
apiVersion: v1
data:
  tls.crt: ''
  tls.key: ''
metadata:
  name: {{ .Values.app.name }}-gateway-credentials
  annotations:
    kubed.appscode.com/sync: "istio-secret-sync=enabled"
type: kubernetes.io/tls
