kind: Secret
apiVersion: v1
data:
  {{ $secret := lookup "v1" "Secret" $.Release.Namespace .Values.ingress.tls.secretName }}
  {{- if $secret }}
  tls.crt: {{ index $secret.data "tls.crt" | default "" | quote }}
  tls.key: {{ index $secret.data "tls.key" | default "" | quote }}
  {{ else }}
  tls.crt: ''
  tls.key: ''
  {{- end }}
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  annotations:
    kubed.appscode.com/sync: "istio-secret-sync=enabled"
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
