apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  encryptedData:
    {{ if eq .Values.app.deploymentEnv "staging" }}
    authClientCredentials: AgACUaQKdWfvuPLXi49v7hpbZMzDUv8SjiC8toSkBM72b3oaG2WgwdVhppVjwwWWKhrrgFDdUVTHIZANp/aNu6/6oZn9pqrY5RvBZ+HNXXcseOl8Mqtx1EwjyOkWRJ5FXq5Wy48vYnE7dkq40HmcYg3nOeBfSqJJzKJnrOhVeBmi5T+C1FH6Q94MUlsCkuSM/EvK9uCEX/7wyxWzzhpiNOdsP6VbOse/Ex3UuDHkOeNSkbO4NVtbdVnkyv/siHX+yngUA1DJJTbmUaNouaa42Q7sacnNLIDS8/NIKBZjJhRUxTODzp01EVhQ+nX+a4cBYSn8GQrqbqozb0p5KDR0W9U+9FC2+UMVRc0I2URgtVV7ckYeGdGT1s3SBDkZkJL6dQ16Y+Yi3xrUD36zBi0dgildY+TQp5suOvtEO8VKtkPugyr2hFIzAyjiVItEOXrZrF58rsxeEhJ9ROv+EeBzGOGk+qKYVdRTfsDX9LIDnpHcFrxS4cDuQLJT/v8A80JvAwZDCxr5KmHgS0CjCrGmPpc1IKXMDp9KeWko5ew2Ahr/fMhl1MqKnXuteY3YfkYJDFYCW6EJOzoEfDUtBkAoRe//gy/lClmb9mCyDw5ogO83/du0LcfRqp7yZBebMEViQV7dOzNbxoOMjRV8GMepK+qYoi8SW7GgtrCbzsqIKppOGDaeaxuOc3HnCOoeOOKACV2ZQxKpKIur87H2rfWfsyS1OjroZStxqVyXhBrXLmFZxchz
    {{ end }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}
      name: {{ .Values.app.name }}
      namespace: bpa
    type: Opaque

