apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  encryptedData:
    authClientCredentials: {{ .Values.app.authClientCredentials }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}
      name: {{ .Values.app.name }}
    type: Opaque
