apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    name: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
